name: lingedge1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'  # 더 넓은 범위의 SDK 버전 지원

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # 기본 아이콘
  cupertino_icons: ^1.0.5  # 안정적인 버전
  
  # 인증 및 API 관련
  http: ^1.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0  # 안정적인 버전
  google_sign_in: ^6.1.4
  
  # 국제화
  intl: ^0.19.0  # Flutter 3.x와 호환되는 안정적인 버전
  
  # 유효성 검사
  email_validator: ^2.1.17
  
  # 파일 관련
  path_provider: ^2.1.0
  open_file: ^3.3.2
  file_picker: ^5.5.0
  permission_handler: ^10.4.5
  
  # URL 실행 (추가 필요)
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # 안정적인 버전

flutter:
  uses-material-design: true
